alias cm="chezmoi"
alias cme="chezmoi edit"
alias cma="chezmoi apply"
alias cmd="chezmoi diff"
alias cmu="chezmoi update"
alias dev="~/developer/personal"
alias grep="grep --color=auto"
alias ls="lsd --icons"
alias l="ls -l"
alias lla="ls -la"
alias tree="ls --tree --level=4"
alias cat="bat"
alias f="fzf --preview 'bat --color=always --style=header,grid --line-range :500 {}'"
alias fo='open "$(f)"'
alias fe='nvim "$(f)"'
alias x="exit"
alias gpg-check="gpg --decrypt ~/test.gpg"
alias lg="lazygit"
alias zj="zellij"
alias p="pnpm"
