[general]
import = ["~/.config/alacritty/themes/cyberdream.toml"]

[terminal.shell]
program = "zsh"

[font]
size = 13.0

[font.normal]
family = "TX-02-AREMU"

[font.offset]
y = 7

[window]
opacity = 0.9
blur = true
dynamic_padding = true
startup_mode = "Windowed"

[window.padding]
x = 5
y = 0

[cursor.style]
shape = "Beam"
blinking = "On"

[scrolling]
multiplier = 2

[mouse]
hide_when_typing = true
