#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config layout bsp

yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config auto_balance on

# float system preferences
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='^Archive Utility$' manage=off

# float settings windows
yabai -m rule --add title='Settings$' manage=off

yabai -m rule --add title='^Extension' manage=off

yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Alacritty$" manage=off
yabai -m rule --add app="^neovide$" manage=off
yabai -m rule --add app="^Roon$" manage=off

yabai -m rule --apply
