set -goq @evergarden_variant "fall"
set -goq @evergarden_accent "green"
set -goq @window_left_separator "█"
set -goq @window_right_separator "█"
set -goq @current_command "#W"

source -F "#{d:current_file}/themes/evergarden-#{@evergarden_variant}-#{@evergarden_accent}.conf"

# messages
set -gF message-style "fg=#{@thm_crust},bg=#{@thm_accent},align=centre"
set -gF message-command-style "fg=#{@thm_text},bg=#{@thm_crust},align=centre"

# pane number indicator
set-option -gF display-panes-colour "#{@thm_accent}"
set-option -gF display-panes-active-colour "#{@thm_accent}"

# status line
set -gF status-style "bg=#{@thm_mantle},fg=#{@thm_text}"
set -gq @status_surface "#{@thm_surface0}"

# status left
set -gF status-left ""

# current_window
set -gq @_wc_left \
	"#[fg=#{@status_surface},bg=default]#{@window_left_separator}"
set -gq @_wc_right \
	"#[fg=#{@status_surface},bg=default]#{@window_right_separator}"
set -gq @_wc_number \
	"#[fg=#{@thm_accent},bg=#{@status_surface}]##I "
set -gq @_wc_text \
	"#[fg=#{@thm_subtext1},bg=#{@status_surface}] #{@current_command}"

set -gF window-status-current-format \
  "#[fg=default,bg=default]#{E:@_wc_left}#{E:@_wc_text} #{E:@_wc_number}#{E:@_wc_right}"

# inactive_window
set -gq @_w_left \
	"#[fg=#{@status_surface},bg=default]#{@window_left_separator}"
set -gq @_w_right \
	"#[fg=#{@status_surface},bg=default]#{@window_right_separator}"
set -gq @_w_number \
	"#[fg=#{@thm_accent},bg=#{@status_surface}]##I "
set -gq @_w_text \
	"#[fg=#{@thm_overlay1},bg=#{@status_surface}] #{@current_command}"

set -gF window-status-format \
  "#[fg=default,bg=default]#{E:@_w_left}#{E:@_w_text} #{E:@_w_number}#{E:@_w_right}"

# status right
set -gq @_s_left \
	"#[fg=#{@status_surface},bg=default]#{@window_left_separator}"
set -gq @_s_right \
	"#[fg=#{@status_surface},bg=default]#{@window_right_separator}"
set -gq @_s_text \
  "#[fg=#{@thm_text},bg=#{@status_surface}] #{b:pane_current_path} "

set -gF status-right "#{E:@_s_left}#{E:@_s_text}#{E:@_s_right}"

# vim: ft=tmux
