[mgr]
prepend_keymap = [
  { on = [
    "E",
  ], run = "plugin eza-preview", desc = "Toggle tree/list dir preview" },
  { on = [
    "-",
  ], run = "plugin eza-preview inc-level", desc = "Increment tree level" },
  { on = [
    "_",
  ], run = "plugin eza-preview dec-level", desc = "Decrement tree level" },
  { on = [
    "$",
  ], run = "plugin eza-preview toggle-follow-symlinks", desc = "Toggle tree follow symlinks" },
  { on = [
    "*",
  ], run = "plugin eza-preview toggle-hidden", desc = "Toggle hidden files" },
]
