[mgr]
prepend_keymap = [
  # eza-preview keymaps
  { on = [
    "e",
    "t",
  ], run = "plugin eza-preview", desc = "Toggle tree/list dir preview" },
  { on = [
    "e",
    "-",
  ], run = "plugin eza-preview inc-level", desc = "Increment tree level" },
  { on = [
    "e",
    "_",
  ], run = "plugin eza-preview dec-level", desc = "Decrement tree level" },
  { on = [
    "e",
    "$",
  ], run = "plugin eza-preview toggle-follow-symlinks", desc = "Toggle tree follow symlinks" },
  { on = [
    "e",
    "*",
  ], run = "plugin eza-preview toggle-hidden", desc = "Toggle hidden files" },
  { on = [
    "e",
    "g",
    "i",
  ], run = "plugin eza-preview toggle-git-ignore", desc = "Toggle .gitignore files" },
  { on = [
    "e",
    "g",
    "s",
  ], run = "plugin eza-preview toggle-git-status", desc = "Toggle showing git status" },
  # yamb keymaps
  { on = [
    "u",
    "a",
  ], run = "plugin yamb save", desc = "Add bookmark" },
  { on = [
    "u",
    "g",
  ], run = "plugin yamb jump_by_key", desc = "Jump bookmark by key" },
  { on = [
    "u",
    "G",
  ], run = "plugin yamb jump_by_fzf", desc = "Jump bookmark by fzf" },
  { on = [
    "u",
    "d",
  ], run = "plugin yamb delete_by_key", desc = "Delete bookmark by key" },
  { on = [
    "u",
    "D",
  ], run = "plugin yamb delete_by_fzf", desc = "Delete bookmark by fzf" },
  { on = [
    "u",
    "A",
  ], run = "plugin yamb delete_all", desc = "Delete all bookmarks" },
  { on = [
    "u",
    "r",
  ], run = "plugin yamb rename_by_key", desc = "Rename bookmark by key" },
  { on = [
    "u",
    "R",
  ], run = "plugin yamb rename_by_fzf", desc = "Rename bookmark by fzf" },
]
