[mgr]
cwd = { fg = "#B9AFA5" }

hovered         = { reversed = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#CAA9A0", bold = true, italic = true, underline = true }
find_position = { fg = "#AFB2A9", bg = "reset", bold = true, italic = true }

marker_copied   = { fg = "#F09A8B", bg = "#F09A8B" }
marker_cut      = { fg = "#91928E", bg = "#91928E" }
marker_marked   = { fg = "#B9AFA5", bg = "#B9AFA5" }
marker_selected = { fg = "#CAA9A0", bg = "#CAA9A0" }

tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

count_copied   = { fg = "#C6AA95", bg = "#F09A8B" }
count_cut      = { fg = "#C6AA95", bg = "#91928E" }
count_selected = { fg = "#C6AA95", bg = "#CAA9A0" }

border_symbol = "│"
border_style  = { fg = "#F09A8B" }

syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#C6AA95", bg = "#C6AA95" }

mode_normal = { bg = "#B9AFA5", bold = true }
mode_select = { bg = "#91928E", bold = true }
mode_unset  = { bg = "#91928E", bold = true }

progress_label  = { bold = true }
progress_normal = { fg = "#B9AFA5", bg = "#2E3131" }
progress_error  = { fg = "#91928E", bg = "#2E3131" }

permissions_t = { fg = "#F09A8B" }
permissions_r = { fg = "#CAA9A0" }
permissions_w = { fg = "#91928E" }
permissions_x = { fg = "#B9AFA5" }
permissions_s = { fg = "#C6AA95" }

[select]
border   = { fg = "#B9AFA5" }
active   = { fg = "#AFB2A9", bold = true }
inactive = {}

[input]
border   = { fg = "#B9AFA5" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "#B9AFA5" }
active   = { reversed = true }
inactive = {}

icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "#B9AFA5" }
title   = {}
hovered = { fg = "#AFB2A9", underline = true }

[which]
cols            = 3
mask            = { bg = "#2E3131" }
cand            = { fg = "#DDA38F" }
rest            = { fg = "#CAA9A0" }
desc            = { fg = "#AFB2A9" }
separator       = "  "
separator_style = { fg = "#CAA9A0" }

[help]
on      = { fg = "#B9AFA5" }
run     = { fg = "#AFB2A9" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#C6AA95", bg = "#B9AFA5" }

[notify]
title_info  = { fg = "#F09A8B" }
title_warn  = { fg = "#CAA9A0" }
title_error = { fg = "#91928E" }

icon_info  = ""
icon_warn  = ""
icon_error = ""

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#B9AFA5" },

	# Media
	{ mime = "{audio,video}/*", fg = "#AFB2A9" },

	# Archives
	{ mime = "application/*zip", fg = "#91928E" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#91928E" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#B9AFA5" },

	# Fallback
	{ name = "*", fg = "#DDA38F" },
	{ name = "*/", fg = "#F09A8B" }
]

