show_symlink = true

[preview]
image_filter = "triangle"
image_quality = 90

[mgr]
show_hidden = true

[[plugin.prepend_previewers]]
name = "*/"
run = "eza-preview"

[[plugin.prepend_previewers]]
name = "*.md"
run = "glow"
