# cyberdream theme for kitty

foreground              #ffffff
background              #16181a
cursor                  #ffffff
cursor_text_color       #16181a
selection_foreground    #ffffff
selection_background    #3c4048

active_tab_foreground   #16181a
active_tab_background   #5ea1ff
inactive_tab_foreground #ffffff
inactive_tab_background #3c4048

active_border_color     #5ea1ff
inactive_border_color   #3c4048
bell_border_color       #ff6e5e

# Normal
color0  #16181a
color1  #ff6e5e
color2  #5eff6c
color3  #f1ff5e
color4  #5ea1ff
color5  #bd5eff
color6  #5ef1ff
color7  #ffffff

# Bright
color8  #3c4048
color9  #ff6e5e
color10 #5eff6c
color11 #f1ff5e
color12 #5ea1ff
color13 #bd5eff
color14 #5ef1ff
color15 #ffffff
