foreground         #E9D1D9
background         #0F1014
cursor             #BCA5B5

active_tab_foreground     #0F1014
active_tab_background     #E9D1D9
inactive_tab_foreground   #E9D1D9
inactive_tab_background   #0F1014

active_border_color   #E9D1D9
inactive_border_color #0F1014
bell_border_color     #777BA0

color0      #37383C
color1		#777BA0
color2		#8F7990
color3		#6B82AB
color4		#8B81A3
color5		#AA7F9A
color6		#C07C93
color7		#D7B5C1
color8		#967F87
color9		#777BA0
color10		#8F7990
color11		#6B82AB
color12		#8B81A3
color13		#AA7F9A
color14		#C07C93
color15		#D7B5C1
